/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import org.testng.annotations.Test;

public class PriorityTest {

    @Test(priority = 3)
    public void registerUser3() {
        System.out.println("registerUser3");
    }
    @Test(priority = 2)
    public void registerUser2() {
        System.out.println("registerUser2");
    }
    @Test(priority = 1)
    public void registerUser1() {
        System.out.println("registerUser1");
    }
}
